version: "~> 1.0"
os: linux
language: shell
services: docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: YX8yZWvHUyABcadmyJM9xO2rFdYWCrLybC0q7nKCvXxxUUUE0knS6aWOiuYfKwBVG/y24Nzkk4DAlO/LpDX0JarQ39yeKJwpf3vcppqI5mhpW6hbI8m8xTxlIaDalowWaWmuDyIq1BlK0ilghbYwJuFuPhyc3SxD7kOPUxXuXB1ph4TkZ6v4Ab8g4DO00l1WyVJBc0Rat2KnD2KqIHvoqIaqd1sO63DxhUQR0I6uIyuOZkUXI84qVCQmMzSlja/N5ppVCYbkAdDBg2/fWT9zF7xtB56y0VueZfa7QbSyB6nKskXyTDSDKGjNmvNQ3dkceIxvyW1rIhcO4q3j7f6Qc0/akEGXhaoikXCGw2fmAM9oG7g3puNk+J5r8Nr95dAU8p0nmE3i9IRbkdBH1DzrspIwYcCT5tbLeQq6zfYHVCJ76WC/9KgDQaperkF2H3ygrpoo/LR5UcazeyIcXYarQabJNTuVUrQgMvL3kgDZa/hMb16XcWd88Dr2os3FMVWZF2AnqHZlJQclQnSU10zIH7NuiUHtnKgjQlvSyfMGfYaHewaTtFM8uMrSfc8lCm9dOJBZ1OnmE74Yyp1mux1q6t4YQISBQRybzk0qnqRO9FW0PX6pA9D+/POE6uP9nis9g7U0fqKb5ChcXvwIUfTkvMYbhHOpJ5eNbcWwAhCflt4=
    template:
      - "%{commit_subject}"
      - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
      - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
env:
  jobs:
    - REPO='aws' TAG='latest' MICROSCANNER_OPTIONS='--continue-on-failure'
script:
  - |
    set -ex
    docker build -t ${ORGANIZATION}/${REPO}:${TAG} --no-cache . 
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      .travis/security-scan.sh ${ORGANIZATION}/${REPO}:${TAG}
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker push ${ORGANIZATION}/${REPO}
      fi
    else
      echo "security scan does not run for pull request. For further information see: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions"
    fi
